# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-metrics-server
  description: This component creates a Helm release for [metrics-server](https://github
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
